I don't move ai logic to separate module, but have addressed other issues
IliaYusov/TicTacToe-with-AI pull request #1
Opened 2020-10-02 15:13 UTC by IliaYusov

2020-10-02 15:14 UTC, IliaYusov commented
@itimky check please this humble pull request :)

2020-10-03 16:07 UTC, itimky commented on .gitgnore
> +# Created by .ignore support plugin (hsz.mobi)
Лучше не использовать такие генераторы.
Тут исключаются файлы на все случаи жизни, и разобраться в таком файле тяжело.
Но это не критично

2020-10-09 21:41 UTC, itimky requested changes

2020-10-09 21:41 UTC, itimky commented on tictactoe_with_ai.py
>  class TicTacToeAI:
А почему решили не выносить в отдельный модуль?

2020-10-09 21:41 UTC, itimky commented on tictactoe_with_ai.py
> +    def __del__(self):  # dumping best moves to file
Этот метод почти никогда не вызывается, поэтому полагаться на него не имеет смысла.
Поскольку любой класс – контейнер, то его удалением занимается Garbage Collector, но он не обязан сразу же удалять этот объект из памяти. Даже если вызвать del <cls_instance>, GC может его не удалять.

Для случаев, когда нужно что-то записать/удалить после обработки, используют ContextManager.
Так же можно в main все обернуть в try..except..finally. В блоке try загружать, а в блоке finally записывать. Но такой поход грязнее.

Если использовать ContextManager, то в main можно написать что-то вроде
```
with MoveManager() as pickles:
    p1 = players[command[1]](pickles)
    ....
```

2020-10-09 21:41 UTC, itimky commented on .gitgnore
> +### Python template
Такие бинарники, как `moves.pickle`, не стоит хранить в репозитории, стоит его добавить в .gitignore. Эти ходы придется просчитать только при первом запуске, поэтому это не страшно.
Так же при игре этот бинарник у меня поменялся, и git показывает изменения, что нехорошо.

2020-10-30 11:54 UTC, IliaYusov commented on .gitgnore
> +# Created by .ignore support plugin (hsz.mobi)
поправил

2020-10-30 11:55 UTC, IliaYusov commented on .gitgnore
> +### Python template
поправил

2020-10-30 13:15 UTC, IliaYusov commented on tictactoe_with_ai.py
> +    def __del__(self):  # dumping best moves to file
А разве при окончании работы скрипта не вызывается? Я на это рассчитывал. 
Сделал Context Manager

2020-10-30 17:13 UTC, itimky commented on tictactoe_with_ai.py
> +    def __del__(self):  # dumping best moves to file
Действительно, при завершении скрипта `__del__` вызвался. Но при этом он все равно он неочевиден: при добавлении циклической ссылки `__del__` у меня вызвался дважды. Можно следить за отсутствием циклических ссылок, но тут будет играть роль человеческий фактор, можно не углядеть. А еще циклические ссылки могут быть удобными, поэтому избегать их тоже неправильно.
Лучше просто не использовать `__del__` (за исключением экзотических ситуаций).

Так же использование `__del__`  – довольно нераспространенная практика, в том числе из-за сложности восприятия кода. При наличии Context Manager легче разобраться что происходит.

2020-10-30 17:16 UTC, merged